export const VIEW_READY = "VIEW_READY",
  TOGGLE_LOCATE = "TOGGLE_LOCATE",
  TOGGLE_SHARE = "TOGGLE_SHARE",
  TOGGLE_FILTER = "TOGGLE_FILTER",
  FETCH_ITEM_INFO = "FETCH_ITEM_INFO",
  UPDATE_LAYER_DEFINITION = "UPDATE_LAYER_DEFINITION";
